### PR TITLE
Fix #149 setting emailOptional to false tries to create a user even where email doesn't exist

### LINKED ISSUE #149: Setting emailOptional to false still tries to create a user when an email does not exist
This issue was initially discussed here: https://github.com/strongloop/loopback-component-passport/pull/70/files#diff-441c92c018846ec2058d6d670e18d258R119

When setting the `emailOptional` config option to `false` a user is still created (unless the user model specifically has a validation requiring an email address).

I was able to reproduce this bug by:
1. Setting the `emailOptional` config option to `false`
2. Authenticating with a profile that doesn't include an email address

### PR DESCRIPTION
**Pull request by alexpls**
More details about the issue on #149

This was due to a error callback being returned inside a process.nextTick block, which was then letting subsequent code execute and create a new user.

This pull request removes the `process.nextTick` to prevent the code from falling through and adds some more tests around this functionality.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by BerkeleyTrue** [comment]
This should be merged as quickly as possible

**Comment by BerkeleyTrue** [comment]
Any reason this hasn't been merged in yet? This is a critical bug

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@BerkeleyTrue Could you rebase your code to pass the Commit Linter? Thanks.

@raymondfeng This is a major bug. One line's fix. Please review it whenever you have time. Thanks!

**Comment by BerkeleyTrue** [comment]
@jannyHou Not my pr. @alexpls Do you have time to rebase?

**Comment by jannyHou** [comment]
@BerkeleyTrue ah..sorry. @alexpls I think your commit msg has format problem. 
I will find the commit linter doc for you asap.

File: lib/models/user-identity.js [hunk 1]
```diff
@@ -121,9 +121,7 @@
                        loopback.getModelByType(loopback.User);
        var userObj = (options.profileToUser || profileToUser)(provider, profile, options);
        if (!userObj.email && !options.emailOptional) {
-         process.nextTick(function() {
-           return cb('email is missing from the user profile');
-         });
+         return cb('email is missing from the user profile');
```
Comment (raymondfeng) [inline lib/models/user-identity.js]: The fix should be as follows:
```
process.nextTick(function() {
  return cb('email is missing from the user profile');
});
return;
```

Comment (alexpls) [inline lib/models/user-identity.js]: Thanks, I've made the change now. Just out of curiosity why do we need the callback to be called in a `nextTick()`? Since we need to return out of that function immediately if the email doesn't exist shouldn't it be fine if we just return the callback straight away?

**Comment by alexpls** [comment]
@jannyHou I've updated the PR to shorten the first line of its commit message to less than 50 chars. Hopefully that will pass the Commit Linter now!

**Comment by jannyHou** [comment]
@slnode test please

File: lib/models/user-identity.js (hunk 1 above)
Comment (jannyHou) [inline lib/models/user-identity.js]: @alexpls Please check this article to see the benefit of using `nextTick()`: http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony

**Comment by jannyHou** [comment]
@alexpls Yeah I understand the linter report is intranet access only. 
I copied the report for you:
```
*************************************************
**
**  Linting commit logs
**
**  2 problems found:
**    9a6d37c - Fix creating user despite missing email address: line 3 longer than 72 characters.
**    9a6d37c - Fix creating user despite missing email address: line 5 longer than 72 characters.
**
**************************************************
```

I also suggest that to keep concise, you can simply shorten the description as 
```
Fixs issue #149 
```
Then when people see it, they will go to the issue or your pr to see details.

**Comment by jannyHou** [comment]
@slnode test please

**Comment by alexpls** [comment]
Ah, okay. Thanks! I have shortened those line lengths now and the linter seems happy :+1:

File: lib/models/user-identity.js (hunk 1 above)
Comment (alexpls) [inline lib/models/user-identity.js]: Will do, thanks.

**Comment by jannyHou** [comment]
@raymondfeng ^^^ The pr passes all test and seems ready to land. PTAL. Thanks :)

**Comment by alexpls** [comment]
It's been a few months since I submitted this PR during which time changes in master branch have created conflicts with its commits. I'm happy to rebase from `master` if this is still something you'd like to get merged in.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

File: test/model.user-identity.test.js [hunk 2]
```diff
@@ -244,4 +244,57 @@ describe('UserIdentity', function() {
...
+    function customProfileToUser(provider, profile, options) {
+      var userInfo = {
+        username: profile.username,
+        password: 'secret',
+      };
+      if (profile.emails && profile.emails[0] && profile.emails[0].value) {
+        userInfo.email = profile.emails[0].value;
+      }
+      return userInfo;
+    }
```
Comment (superkhau) [inline test/model.user-identity.test.js]: Move to bottom of function of describe block please: https://github.com/strongloop/loopback-contributor-docs/blob/master/style-guide.md#good-8

cc @jannyHou

File: test/model.user-identity.test.js [hunk 3]
```diff
@@ -244,4 +244,57 @@ describe('UserIdentity', function() {
...
+
+    it('creates a user when given an email address', function(done) {
+      UserIdentity.login('facebook', 'oAuth 2.0', {
+        emails: [{ value: 'abc123@fb.com' }],
```
Comment (superkhau) [inline test/model.user-identity.test.js]: use abc123@example.com

See https://github.com/strongloop/loopback-contributor-docs/pull/8/files

File: test/model.user-identity.test.js [hunk 4]
```diff
@@ -244,4 +244,57 @@ describe('UserIdentity', function() {
...
+        id: 'fbi123',
+        username: 'fbu123',
+      }, {
+        accessToken: 'at1',
+        refreshToken: 'rt1',
+      }, {
+        emailOptional: false,
+        profileToUser: customProfileToUser,
+      }, function(err, user, identity, token) {
+        assert(!err, 'No error should be reported');
```
Comment (superkhau) [inline test/model.user-identity.test.js]: `if (err) return done (err);` for better stack traces.

File: test/model.user-identity.test.js [hunk 5]
```diff
@@ -244,4 +244,57 @@ describe('UserIdentity', function() {
...
+        assert(user, 'User instance should be returned');
```
Comment (superkhau) [inline test/model.user-identity.test.js]: You should verify the user instance returned has the correct values (ie. the correct user was returned after you logged in).

File: test/model.user-identity.test.js [hunk 6]
```diff
@@ -244,4 +244,57 @@ describe('UserIdentity', function() {
...
+        done();
+      });
+    });
+
+    it('does not create a user if not given an email address', function(done) {
```
Comment (superkhau) [inline test/model.user-identity.test.js]: it does not create a user if an email address was not given

File: test/model.user-identity.test.js [hunk 7]
```diff
@@ -244,4 +244,57 @@ describe('UserIdentity', function() {
...
+        UserIdentity.login('facebook', 'oAuth 2.0', {
+          id: 'fbi234',
+          username: 'fbu234',
+        }, {
+          accessToken: 'at2',
+          refreshToken: 'rt2',
+        }, {
+          emailOptional: false,
+          profileToUser: customProfileToUser,
+        }, function(err, user, identity, token) {
```
Comment (superkhau) [inline test/model.user-identity.test.js]: if (err) return done(err);

File: test/model.user-identity.test.js [hunk 8]
```diff
@@ -244,4 +244,57 @@ describe('UserIdentity', function() {
...
+          assert(err.match(/email is missing/), 'Should report error');
+          assert(typeof user === 'undefined', 'Should not return a user instance');
+          User.count(function(err, countAfter) {
```
Comment (superkhau) [inline test/model.user-identity.test.js]: if (err) return done(err);

**Comment by superkhau** [comment]
@alexpls Reviewed, mostly LGTM. Please address and we can get it landed. @jannyHou You can take it from here.

**Comment by superkhau** [comment]
@alexpls Please rebase too while you're at it.

**Comment by alexpls** [comment]
Thank you @superkhau. Actioned your feedback and rebased from master.

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@slnode test please

**Comment by alexpls** [comment]
@jannyHou I see there's a test failure that's come up on one of the CI builds. Let me know if there's a fix you want me to look into.

**Comment by jannyHou** [comment]
@alexpls Thank you. The failing machine is using node 5.x and macos:
I post the failing report here:
```
 1) UserIdentity emailOptional set to false creates a user when given an email address:
     Uncaught AssertionError: LOGIN_FAILED
      at test/model.user-identity.test.js:214:11
      at tokenHandler (node_modules/loopback/common/models/user.js:239:9)
      at node_modules/loopback-datasource-juggler/lib/relation-definition.js:1817:13
      at node_modules/loopback-datasource-juggler/lib/dao.js:381:19
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:122:5)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
      at ModelConstructor.<anonymous> (node_modules/loopback-datasource-juggler/lib/dao.js:380:23)
      at ModelConstructor.next (node_modules/loopback-datasource-juggler/lib/hooks.js:83:12)
      at ModelConstructor.<anonymous> (node_modules/loopback-datasource-juggler/lib/dao.js:368:26)
      at ModelConstructor.next (node_modules/loopback-datasource-juggler/lib/hooks.js:83:12)
      at node_modules/loopback-datasource-juggler/lib/dao.js:367:22
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
      at doNotify (node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:122:5)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
      at Function.ObserverMixin._notifyBaseObservers (node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
      at Function.ObserverMixin.notifyObserversOf (node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
      at createCallback (node_modules/loopback-datasource-juggler/lib/dao.js:357:17)
      at node_modules/loopback-datasource-juggler/lib/connectors/memory.js:189:19
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)



/Users/jenkins/build/workspace/loopback-component-passport/86a05863/node_modules/mocha/lib/runner.js:526
      if (test.isPending()) {
              ^

TypeError: Cannot read property 'isPending' of undefined
    at /Users/jenkins/build/workspace/loopback-component-passport/86a05863/node_modules/mocha/lib/runner.js:526:15
    at next (/Users/jenkins/build/workspace/loopback-component-passport/86a05863/node_modules/mocha/lib/runner.js:349:14)
    at /Users/jenkins/build/workspace/loopback-component-passport/86a05863/node_modules/mocha/lib/runner.js:359:7
    at next (/Users/jenkins/build/workspace/loopback-component-passport/86a05863/node_modules/mocha/lib/runner.js:285:14)
    at Immediate._onImmediate (/Users/jenkins/build/workspace/loopback-component-passport/86a05863/node_modules/mocha/lib/runner.js:327:5)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by alexpls** [comment]
@jannyHou Strange... I can't replicate that test failure. I just tried on node v5.12.0 and OS X 10.11.6 and all tests passed for me.

**Comment by jannyHou** [comment]
@alexpls It's not a required one now, probably failed due to config error.

Cheers please go ahead and merge it! 🚢

**Comment by superkhau** [comment]
test please

**Comment by jannyHou** [comment]
oops sorry I didn't notice that there are new commits now. @alexpls Could you rebase your code again? Sorry for the delay.

**Comment by alexpls** [comment]
@jannyHou Okay thanks! Rebased again now.

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
All green 🚢  @alexpls I believe this time you can merge it!

**Comment by superkhau** [comment]
@jannyHou Feel free to take over this PR to get it landed if you have time (with the changes requested of course).

File: test/model.user-identity.test.js [hunk 9]
```diff
@@ -239,4 +239,60 @@ describe('UserIdentity', function() {
       done();
     });
   });
+
+  describe('emailOptional set to false', function(err) {
+    it('creates a user when given an email address', function(done) {
+      var username = 'fbu123';
+      UserIdentity.login('facebook', 'oAuth 2.0', {
+        emails: [{value: 'abc123@example.com'}],
```
Comment (alexpls) [inline test/model.user-identity.test.js]: Yes, I've verified that the emails param accepts an array of objects with a `value` key.

**Comment by alexpls** [comment]
@superkhau @jannyHou Thanks for the review. I've actioned those changes and have also squashed my commits into one.

File: test/model.user-identity.test.js (hunk 9 above)
Comment (superkhau) [inline test/model.user-identity.test.js]: I mean can you put `emails: {value: 'abc123@example.com'}`, meaning can we simplify it to take ONE object directly instead of an Array with one object.

**Comment by alexpls** [comment]
@superkhau Ah okay I see what you mean, good point. I've simplified the code in that test now.

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@alexpls I believe it's good to land now 🚢 ! All test pass.

**Comment by alexpls** [comment]
@jannyHou Great! Will you merge it in? I don't have merge access on this repo.
